start_program:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: homeconnect_ws
    start_in:
      required: false
      selector:
        duration:

set_start_in:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: homeconnect_ws
    start_in:
      required: true
      selector:
        duration:
