name: Report an issue with Home Connect Local
description: Report an issue with Home Connect Local.
labels: ["bug"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Provide a clear description of the problem.
  - type: textarea
    attributes:
      label: Diagnostics information
      placeholder: "drag-and-drop the diagnostics file here"
      description: >-
        [Download the Integration Diagnostics](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics) and drag-and-drop that file into the textbox below.
  - type: textarea
    attributes:
      label: Debug log
      placeholder: "drag-and-drop the debug log file here"
      description: >-
        Check the README for instructions on how to enable debug logging, then drag-and-drop that file into the textbox below.
        The log should at least contain one reload of config entry
  - type: textarea
    attributes:
      label: Description files
      placeholder: "drag-and-drop the Description files here"
      description: >-
        If you are unable to add a new Appliance, upload the `*_DeviceDescription.xml` and `*_FeatureMapping.xml` files from the Profile File here.
