name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  validate:
    needs: lint
    uses: ./.github/workflows/validate.yaml
  test:
    needs: [lint, validate]
    uses: ./.github/workflows/test.yaml
